apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/prasanth624/blue-green-deployment-k8s.git
    targetRevision: HEAD
    path: ./ 

  destination:
    server: https://kubernetes.default.svc
    namespace: blue-green-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

